# Generated by Django 4.0.3 on 2022-04-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='image')),
            ],
            options={
                'db_table': 'tweet',
            },
        ),
    ]
