# Generated by Django 4.0.3 on 2022-04-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_tweet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-date_time_created'], 'verbose_name': 'Tweet', 'verbose_name_plural': 'Tweets'},
        ),
    ]
